# .gitlab-ci-template.yml

stages:
  - build
  - push
  - deploy

variables:
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

build_docker_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE .
  artifacts:
    paths:
      - Dockerfile
      - .dockerignore

push_docker_image:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker push $DOCKER_IMAGE

deploy_docker_image:
  stage: deploy
  image: docker:latest
  script:
    - echo "Deploying $DOCKER_IMAGE"
    - docker run -d --rm --name my_app $DOCKER_IMAGE